export const MAX_TODO_HISTORY = 100;
export const POMODORO_WORK_TIME = 25;
export const POMODORO_BREAK_TIME = 5;
export const SECONDS_PER_MINUTE = 60;
export const POMODORO_TOTAL_MINUTES = POMODORO_WORK_TIME + POMODORO_BREAK_TIME;
export const POMODORO_TOTAL_SECONDS = POMODORO_WORK_TIME * SECONDS_PER_MINUTE;
